## ***BOW (Bag Of Words)***
- Creates a vocabulary with all the words present in the training set of data
- Counts the number / frequency of each of the words of its trained vocab in the given text
- Thus the whole text is vectorized

> This can be implemented by **count vectorizer of sklearn** 

In [88]:
import pandas as pd
import numpy as np

In [89]:
data = pd.read_csv('IMDB.csv')
data.shape

(50000, 2)

In [90]:
data.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [91]:
# numeric conversion of the categories
data['sentiment'] = data['sentiment'].apply(lambda x: 1 if x == "positive" else 0)
data.head()

review  sentiment
0  One of the other reviewers has mentioned that ...          1
1  A wonderful little production. <br /><br />The...          1
2  I thought this was a wonderful way to spend ti...          1
3  Basically there's a family where a little boy ...          0
4  Petter Mattei's "Love in the Time of Money" is...          1

In [92]:
data['sentiment'].value_counts()

sentiment
1    25000
0    25000
Name: count, dtype: int64

In [93]:
# test train split
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(data['review'], data['sentiment'], test_size=0.2, random_state=42)

In [94]:
X_train, Y_train

(39087    That's what I kept asking myself during the ma...
 30893    I did not watch the entire movie. I could not ...
 45278    A touching love story reminiscent of ‘In the M...
 16398    This latter-day Fulci schlocker is a totally a...
 13653    First of all, I firmly believe that Norwegian ...
                                ...                        
 11284    `Shadow Magic' recaptures the joy and amazemen...
 44732    I found this movie to be quite enjoyable and f...
 38158    Avoid this one! It is a terrible movie. So wha...
 860      This production was quite a surprise for me. I...
 15795    This is a decent movie. Although little bit sh...
 Name: review, Length: 40000, dtype: object,
 39087    0
 30893    0
 45278    1
 16398    0
 13653    0
         ..
 11284    1
 44732    1
 38158    0
 860      1
 15795    1
 Name: sentiment, Length: 40000, dtype: int64)

In [95]:
X_test, Y_test

(33553    I really liked this Summerslam due to the look...
 9427     Not many television shows appeal to quite as m...
 199      The film quickly gets to a major chase scene w...
 12447    Jane Austen would definitely approve of this o...
 39489    Expectations were somewhat high for me when I ...
                                ...                        
 28567    Although Casper van Dien and Michael Rooker ar...
 25079    I liked this movie. I wasn't really sure what ...
 18707    Yes non-Singaporean's can't see what's the big...
 15200    As far as films go, this is likable enough. En...
 5857     I saw Anatomy years ago -- dubbed at a friends...
 Name: review, Length: 10000, dtype: object,
 33553    1
 9427     1
 199      0
 12447    1
 39489    0
         ..
 28567    0
 25079    1
 18707    1
 15200    0
 5857     1
 Name: sentiment, Length: 10000, dtype: int64)

***counter vector generator model creation***

In [96]:
from sklearn.feature_extraction.text import CountVectorizer

In [97]:
vectorizer = CountVectorizer()

In [98]:
print(dir(vectorizer))

['_CountVectorizer__metadata_request__fit', '_CountVectorizer__metadata_request__transform', '__annotations__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__firstlineno__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__sklearn_clone__', '__sklearn_tags__', '__static_attributes__', '__str__', '__subclasshook__', '__weakref__', '_build_request_for_signature', '_char_ngrams', '_char_wb_ngrams', '_check_stop_words_consistency', '_check_vocabulary', '_count_vocab', '_doc_link_module', '_doc_link_template', '_doc_link_url_param_generator', '_get_default_requests', '_get_doc_link', '_get_metadata_request', '_get_param_names', '_get_params_html', '_html_repr', '_limit_features', '_parameter_constraints', '_repr_html_', '_repr_html_inner', '_repr_mimebun

In [99]:
X_train_cv = vectorizer.fit_transform(X_train)
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 5455841 stored elements and shape (40000, 93003)>

In [100]:
vectorizer.vocabulary_['of']

58067

In [101]:
X_train[0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fa

In [102]:
part = X_train_cv[0].toarray()
part

array([[0, 0, 0, ..., 0, 0, 0]], shape=(1, 93003))

In [103]:
np.where(part[0] != 0)

(array([   49,  1202,  1600,  1712,  1868,  2072,  2112,  2121,  2701,
         3497,  3533,  3544,  4094,  4435,  4647,  4661,  4707,  4894,
         5151,  5534,  5570,  5687,  5927,  6180,  6529,  6868,  6909,
         7934,  8088,  8196,  8404,  8836,  8890,  9098,  9220,  9383,
        10731, 10934, 11486, 11663, 11683, 12092, 12257, 12409, 12460,
        12515, 12827, 13126, 13361, 13601, 13755, 14592, 15647, 16938,
        17153, 17563, 18236, 18861, 20187, 20918, 22019, 22266, 22639,
        22757, 22797, 22932, 23090, 23848, 24232, 24258, 24370, 24726,
        24881, 25421, 26065, 26770, 26986, 27188, 28148, 29134, 29276,
        29301, 29544, 29768, 29820, 30117, 30257, 30318, 31436, 32212,
        32323, 32500, 33523, 33780, 33790, 34187, 34191, 35098, 36386,
        36819, 36905, 36963, 37171, 37193, 37217, 37326, 37530, 38073,
        38261, 38497, 38516, 39128, 39336, 39446, 40055, 40240, 40420,
        40723, 40749, 40819, 41227, 42344, 42704, 42814, 42829, 43991,
      

In [104]:
part[0][58067] # In the text vector at 58067 indexm 7 
# signifies 58067th word of the vocab array appears 7 times in the given text

np.int64(7)

### **Classification**

In [105]:
from sklearn.naive_bayes import MultinomialNB

In [106]:
clf1 = MultinomialNB()

In [107]:
clf1.fit(X_train_cv, Y_train)

MultinomialNB()

In [108]:
clf1.predict(X_train_cv[:4])

array([0, 0, 1, 0])

In [109]:
Y_train[:4]

39087    0
30893    0
45278    1
16398    0
Name: sentiment, dtype: int64

In [111]:
X_test_cv = vectorizer.transform(X_test)

In [112]:
Y_preds = clf1.predict(X_test_cv)

In [113]:
Y_preds[:10]

array([1, 1, 0, 1, 0, 1, 1, 0, 0, 0])

In [114]:
Y_test[:10]

33553    1
9427     1
199      0
12447    1
39489    0
42724    1
10822    1
49498    1
4144     0
36958    0
Name: sentiment, dtype: int64

In [115]:
from sklearn.metrics import classification_report

In [116]:
print(classification_report(y_true=Y_test, y_pred=Y_preds))

              precision    recall  f1-score   support

           0       0.83      0.88      0.85      4961
           1       0.87      0.82      0.85      5039

    accuracy                           0.85     10000
   macro avg       0.85      0.85      0.85     10000
weighted avg       0.85      0.85      0.85     10000

